# Generated by Django 4.1.9 on 2023-05-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.CharField(max_length=20)),
                ('id_vuelo', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=1)),
                ('asiento', models.CharField(max_length=10)),
                ('categoria_pasajero', models.CharField(max_length=20)),
                ('equipaje_mano', models.CharField(max_length=50)),
                ('equipaje_bodega', models.CharField(max_length=50)),
            ],
        ),
    ]
